EntityGraphQL/EntityGraphQL

.gitignore, src/EntityQueryLanguage.DataApi/EntityQueryLanguage.DataApi.csproj, src/EntityQueryLanguage/EntityQueryLanguage.csproj
Changed two things:
- added a few .gitignore entries from opening in VS2017.
- Removed Json.net Dependency. It wasn't being used by anything, and was set to v11. This makes running from an Azure Function annoyingly difficult. Azure Functions have some known issues with locked dependencies, Json.Net being one of them (Functions all run directly in the host, which already is locked to Json.Net 9.0.1). Best to just remove the dependency.
=> Removing Json.net Dependency

src/EntityGraphQL/Compiler/GraphQLResultNode.cs, src/EntityGraphQL/EntityQueryExtensions.cs, src/EntityGraphQL/GraphQLVaildation.cs, src/EntityGraphQL/Schema/GraphQLIgnoreInputAttribute.cs, src/EntityGraphQL/Schema/MappedSchemaProvider.cs, src/EntityGraphQL/Schema/Models/Introspection.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/demo/Controllers/QueryController.cs, src/demo/DemoContext.cs, src/demo/GraphQLSchema.cs
Start of Introspection Query. Summary of changes below. Copied of email for tracking.
- Add Models (folder) namespace to avoid collision with the Field object while working with Introspection return model.
- GraphQLIgnoreInputAttribute will remove the parameter from the INPUT type. Ex: might be to hide a virtual ICollection or navigation property.
- SchemaBuilder.cs: pull description from "ComponentModel.DescriptionAttribute".
- SchemaType.cs: pull description from "ComponentModel.DescriptionAttribute" & changed string.Empty to null. This will allow a new Field to update the ReturnTypeSingle.
- Update Demo with typos, descriptions, and checking for Introspection Query
=> Introspection Query

CHANGELOG.md, src/EntityGraphQL/Compiler/GraphQLMutationNode.cs, src/EntityGraphQL/EntityGraphQL.csproj, src/EntityGraphQL/Schema/GraphQLIgnoreAttribute.cs, src/EntityGraphQL/Schema/GraphQLMutationAttribute.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/tests/EntityGraphQL.Tests/GraphQLIgnoreAttributeTests.cs, src/tests/EntityGraphQL.Tests/MutationTests.cs
fixes #20 
Use `[GraphQLIgnore]` to mark a field as ignored in both Input types and Query schema in EntityGraphQL.
Use `[GraphQLIgnore(GraphQLIgnoreType.Query)]` to mark a field as ignored in the query schema. If the type is also used in a mutation input type, the field is available.
Use `[GraphQLIgnore(GraphQLIgnoreType.Input)]` to ignore a field in a mutation input type if the type is also exposed in the query schema, it will be available.
Note `[GraphQLIgnore]` is shorthand for `[GraphQLIgnore(GraphQLIgnoreType.All)]`
=> split ignore into query and input

src/EntityGraphQL/Schema/SchemaGenerator.cs
When the description contains a " the generated schema is invalid, this pull request replaces " with \\\" in the generated schema.
=> Escape " in Description field when generating schema.

README.md
I had a hard time finding the EQLCompiler class, no wonder it has been renamed, updated the readme to reflect this change.
=> Reflect rename of EQLCompiler -> EntityQueryCompiler in documentation

src/EntityGraphQL/Schema/SchemaType.cs
Get a field by an expression selection on the real type.
A useful overload for the `GetField(string fieldName)` method. It takes an `Expression<Func<TBaseType, object>>` rather than a `string`.
It works just like the overload for the `RemoveField(string fieldName)` method, which currently exists, that method too takes an expression rather than a string and then does the work, which makes our lives easier.
=> GetField by an expression

src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/SchemaType.cs
Currently the `ToCamelCaseStartsLower` is used in some cases and the `FieldNamer` in others, this desync causes errors for example with mutation arguments, giving the error that a field is not found.
I fixed all the easy ones in this pull request, but there are 5 left that don't operate on `MemberInfo` that i have no idea how to fix.
* SchemaGenerator.BuildMutations
* SchemaGenerator.BuildSchemaTypes
* SchemaGenerator.GetGqlArgs
* SchemaGenerator.MakeQueryType
* SchemaIntrospection.BuildFieldsForType
=> Use FieldNamer instead of SchemaGenerator.ToCamelCaseStartsLower.

src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs
Added string and long parsing for DateTime and DateTimeOffset. In my particular use case, I had a field that accepted a `DateTimeOffset` as a parameter. This change allows for the ability to pass that parameter as either a formatted string, or ticks.
```
{
entity(startDate: 637384711224902655, endDate: "2020-10-16T18:54:19.5109301-04:00") {
id
latitude
longtitude
address1
city
country
postalCode
state
}
}
```
=> Added string and long parsing for DateTime and DateTimeOffset

src/EntityGraphQL/EntityGraphQL.csproj, src/tests/EntityGraphQL.Tests/EntityGraphQL.Tests.csproj
Updated Humanizer.Core version because it conflicts with newer version from other packages, for example Microsoft.EntityFrameworkCore.Tools
=> Update Humanizer.Core version

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaProvider.cs
For security issues, introspection can be disabled on production environment.
The argument is associated with the creation of the schemaProvider
=> feat: Add introspection option for production environnment

src/EntityGraphQL/Extensions/TypeExtensions.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
Hi
This is not a big deal, but I need to manipulate dictionary through GraphQL, and I get this error in introspection:
`{"data":{},"errors":[{"message":"Field error: __schema - Value cannot be null. (Parameter 'type')"}]}`
GraphQL is working, but this is painfull to not have introspection to develop the front.
Regards
=> fix: Handling dictionaries introspection

docs/content/schema-creation.md
Changed U+2010 hyphens to U+002D hyphens, because in the text’s font on the web page, the U+2010 hyphens render as a box with an X.
Browser used: Chrome for macOS.
=> Fix hyphen rendering

docs/content/getting-started.md
Recent versions of Entity Framework Core require a name with `UseInMemoryDatabase`.
=> Name the in-memory database

src/EntityGraphQL.AspNet/PolicyOrRoleBasedAuthorization.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs
When a query does not include any fields, all fields are returned even if some fields have been removed via `RemoveField`.
For example, even with this configuration:
``` c#
schema.Type<Person>().RemoveField(p => p.Id);
```
the query `{ people }` returns the `Id` field.
This behavior limits the ability for EntityGraphQL to be used with entity types used internally by the server. It would be convenient to add app's existing entity types to a GraphQL DB context, except with sensitive and incompatible fields removed. However, since a GraphQL client can access all fields, regardless of `RemoveField`, this approach isn't currently viable.
To reproduce this issue, run the test `WildcardQueriesHonorRemovedFields` in this PR.
=> Wildcard queries don't honor removed fields

src/EntityGraphQL/Schema/SchemaProvider.cs
These are useful for mapping to 8-bit database columns.
=> Add default mappings for 8-bit integer types.

docs/content/schema-creation/03-types.md
Various grammar and typo fixes. Also removed the bit about arrays from the context that had mentioned both arrays and IEnumerable<T>, since all arrays already implement IEnumerable<T>.
=> Grammar and redundancy cleanup

src/EntityGraphQL/Schema/MutationField.cs
There are a few other calls to `GetProperties` in the codebase without arguments. It's not clear whether they also should filter their output.
=> Only get types for public instance properties of mutations.

src/EntityGraphQL/Extensions/TypeExtensions.cs, src/EntityGraphQL/Schema/ArgType.cs, src/EntityGraphQL/Schema/GqlTypeInfo.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/Util/NullableReferenceTypeTests.cs
given the following context
```
public class Context
{
public string NonNullable { get; set; } = "";
public string? Nullable { get; set; }   
public IEnumerable<Test> Tests { get; set; } = new List<Test>();
public IEnumerable<Test>? Tests2 { get; set; }
}
```
generate the following query type
```
type Query {
nonNullable: String!
nullable: String
tests: [Test!]!
tests2: [Test!]
}
```
=> add basic support for nullable ref types

docs/content/schema-creation/03-types.md, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/GqlTypeEnum.cs, src/EntityGraphQL/Schema/ISchemaType.cs, src/EntityGraphQL/Schema/Models/Introspection.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaGenerator.cs, src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaProviderTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/TestAbstractDataGraphSchema.cs
Includes changes from https://github.com/EntityGraphQL/EntityGraphQL/pull/139/
* Cleanup SchemaType to use an enum instead of lots of boolean type variables (controversial? i tried to not break any public api)
* Allow types to inherit from multiple base classes/interfaces
* Cleanup Interfaces api a bit - added a "AddAllBaseTypes, AddBaseType<T> and AddBaseType(string)" which provides a lot more flexiblity (there were issues when a type was auto detected before you could add its base type)
=> Multiple inheritance and code cleanup

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaProvider.cs
The descriptions for the `Query` and `Mutations` types can be considered unnecessary, since they are already well-defined types. Users may read the comments expecting to find specific details about a particular GraphQL API, only to end up realizing they are just boilerplate. OTOH, such comments can be useful for new users. It's a tradeoff. Another factor is that tools may not expect description here (see dotansimha/graphql-code-generator#8025).
If a description is ultimately included, better grammar would be like this:
> The query type representing all the entry points into the object graph.
=> Remove boilerplate type descriptions

docs/content/schema-creation/01-mutations.md
The doc changes add additional clarification to mutations, based mainly on the #126 change to using an one instance of the mutation object per request.
=> Mutation controller doc improvements

CHANGELOG.md, docs/content/schema-creation/01-mutations.md, src/EntityGraphQL/EntityGraphQL.csproj, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/MutationField.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/ErrorTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/VariableTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SerializationTests.cs, src/tests/EntityGraphQL.Tests/ValidationTests.cs
Instead of looking a mutation controller up in the service provider which can lead to mis-matched lifetimes of services. Always create a mutation controller per request (using DI for constructor) like asp.net controllers.
=> mutation controllers always created per request

src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs, src/tests/EntityGraphQL.Tests/SerializationTests.cs
If a property in a nested object is nullable
eg Birthdate in below example
```
var body = @"{
""query"": ""mutation AddPerson($names: InputObject){ addPersonInput(nameInput: $names) { id name lastName } }"",
""variables"": { ""names"": { ""name"": ""Lisa"", ""lastName"": ""Simpson"", ""Birthdate"": null } }
}";
```
ExpressionUtil fails to convert it as it defaults it back to empty string then can't convert it to DateTime?
Pretty sure I'd submitted this fix before, but maybe it was a tag along in one of the PRs that got scrapped.
=> bugfix: support for nested nullable objects

docs/content/field-extensions/02-filtering.md, src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/EntityGraphQL/Compiler/Grammer/EntityQL.g4, src/EntityGraphQL/EntityGraphQL.csproj, src/tests/EntityGraphQL.Tests/EntityQuery/GraphQLEntityQueryExtensionTests.cs
small tweaks to filter language 
support for != operator
split logic operators out so precedence is correct
eg you can now do
field2 == "2" or field2 == "2"
instead of just 
(field2 == "2") or (field2 == "2")
=> bugfix: add != to filter language, fix operator precedence

src/EntityGraphQL/Compiler/Util/ArgumentUtil.cs, src/EntityGraphQL/Schema/ArgType.cs, src/EntityGraphQL/Schema/Attributes/GraphQLIgnoreAttribute.cs, src/EntityGraphQL/Schema/MutationField.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationMethodParameterTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs
#146
Although I feel like it could have broken something.
```
[GraphQLMutation]
public Person AddPersonSeparateArguments(string name, List<string> names, InputObject nameInput, Gender? gender)
{
return new Person { Name = string.IsNullOrEmpty(name) ? "Default" : name, Id = 555, Projects = new List<Project>() };
}
```
becomes
```
addPersonSeparateArguments(name: String, names: [String!], nameInput: InputObject, gender: Gender): Person
```
and
```
[GraphQLMutation]
public Person AddPersonSingleArgument(InputObject nameInput)
{
return new Person { Name = string.IsNullOrEmpty(nameInput.Name) ? "Default" : nameInput.Name, Id = 555, Projects = new List<Project>() };
}
```
becomes
```
addPersonSingleArgument(nameInput: InputObject): Person
```
both with auto add input types on.
=> feature: Allow GraphQL mutation arguments as seperate arguments

CHANGELOG.md, docs/content/schema-creation.md, src/EntityGraphQL.AspNet/Extensions/AddGraphQLOptions.cs, src/EntityGraphQL.AspNet/Extensions/EntityGraphQLAspNetServiceCollectionExtensions.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/ISchemaType.cs, src/EntityGraphQL/Schema/MutationField.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaBuilderOptions.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.AspNet.Tests/PoliciesTests.cs, src/tests/EntityGraphQL.Tests/EntityQuery/GraphQLEntityQueryExtensionTests.cs, src/tests/EntityGraphQL.Tests/ErrorTests.cs, src/tests/EntityGraphQL.Tests/IntrospectionTests/MetaDataTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationMethodParameterTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/ArgumentTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/InheritanceTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/VariableTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs, src/tests/EntityGraphQL.Tests/SerializationTests.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs, src/tests/EntityGraphQL.Tests/TestAbstractDataContext.cs
=> SchemaBuilder options

src/EntityGraphQL/Compiler/EntityGraphQLValidationException.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLDirective.cs, src/EntityGraphQL/Compiler/Util/ArgumentUtil.cs, src/EntityGraphQL/Schema/ArgType.cs, src/EntityGraphQL/Schema/BaseField.cs, src/EntityGraphQL/Schema/Field.cs, src/EntityGraphQL/Schema/MutationField.cs, src/EntityGraphQL/Schema/Validators/ArgumentValidatorContext.cs, src/EntityGraphQL/Schema/Validators/DataAnnotationsValidator.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs, src/tests/EntityGraphQL.Tests/ValidationTests.cs
Had a bit of a go at making validation of nested objects and lists working.
* Implemented IArgumentValidator with a basic class that does recursive validation
* Auto register this validator type with BaseField
* should cover all validation attribute types not just the ones you had before
I played around with removing the validation attributes from ArgTypes since it should cover the same things however
* couldn't replace required field validation on non nullable fields as it didn't have access to raw arguments (eg it was getting an object with default values which are technically valid), could probably remove the range/length attribute checking from argtype though just means they'd be caught later
* couldn't find a nice way to remove the throw statements from ArgumentUtil as it would allow …
=> feature: Data annotations validator: validating nested objects

src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
added DateTimeOffset as default scalar, there is no need to add scalar type manually.
exception when DateTimeOffset is used in object graph: "No schema type found for dotnet type DateTimeOffset. Make sure you add it or add a type mapping"
solution:
```c#
services.AddGraphQLSchema<DemoContext>(options =>
{
options.PreBuildSchemaFromContext = (schema) =>
{
schema.AddScalarType<DateTimeOffset>("DateTimeOffset", "Type representing a DateTimeOffset");
};
});
```
=> add DateTimeOffset support

src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/MutationField.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaBuilderOptions.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationMethodParameterTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs, src/tests/EntityGraphQL.Tests/ValidationTests.cs
Follows the other schema builder methods using an options object.
Is a breaking change to the API.
=> fix #203 - breaking change to the add mutations methods to use an options object

src/tests/EntityGraphQL.Tests/QueryTests/ServiceFieldTests.cs
When adding a field implemented through a service, if the implementation is invoked through a static method, the call fails. This PR has a unit test `TestServiceFieldWithStaticMethod`, which results in this error:
> Field 'projects' - variable 'srv' of type 'EntityGraphQL.Tests.ServiceFieldTests+ConfigService' referenced from scope '', but it is not defined
On a production project with a similar configuration, the error I get is effectively:
> ''GetItems_entity, service_' is not a member of type 'Entity' (Parameter 'propertyOrFieldName')'
The reason I was using a static method in the first place is to subvert the use of `Expression`. There is complex business logic that combines data from the entity and service and returns a custom non-entity type. The expression tree is far too complex …
=> Can't implement service via static method.

src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs
A mutation that returns `Task<T>` but doesn't use the keyword causes a runtime exception like:
> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : Cannot convert type 'System.Threading.Tasks.Task<bool>' to 'bool'
This PR contains a test. Related issue: #197.
=> Async mutations without async keyword resolve to wrong type

src/tests/EntityGraphQL.Tests/QueryTests/VariableTests.cs
When passing a required variable of an array type to a query, the conversion operator used to access the wrapped value inside RequiredField throws an exception.
In the unit test in this PR, the failed conversion occurs in the cast `(Guid[])args.ids`. However, the error also occurs in the more subtle case of an implicit conversion, such as if `args.ids` is passed to a method that takes a parameter of type `Guid[]`.
A downstream problem is that the error handling is throwing an NullRefernceException, causing the original exception related to `IConvertable` to not be output.
=> Required array parameter fails conversion

docs/docs/field-extensions/custom-extensions.md, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLField.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLQueryField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLInlineFragmentField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLListSelectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLObjectProjectionField.cs, src/EntityGraphQL/Compiler/Util/CompileHelper.cs, src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/EntityGraphQL/Schema/BaseField.cs, src/EntityGraphQL/Schema/Field.cs, src/EntityGraphQL/Schema/FieldExtensions/BaseFieldExtension.cs, src/EntityGraphQL/Schema/FieldExtensions/ConnectionPaging/ConnectionEdgeExtension.cs, src/EntityGraphQL/Schema/FieldExtensions/IFieldExtension.cs, src/EntityGraphQL/Schema/FieldToResolve.cs, src/EntityGraphQL/Schema/IField.cs, src/EntityGraphQL/Schema/MutationField.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/QueryTests/UnionTests.cs
So we can better tell same name fields from different types apart for union types
@bzbetty thoughts on this instead of replacing the name to insert the type in one spot and removing it later?
Seems knowing the type the field came from would be useful elsewhere too.
=> Hold the type a field  belongs to

src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs
This PR adds a test that mutation that takes its arguments separately (vs via a `MutationArguments` object) works when the GraphQL query passes the parameters directly, rather than via a GraphQL variable.
=> Mutations with separate parameters fail if called without variables

src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs
It is common for an exception from a field resolution method to be wrapped twice in `TargetInvocationException`. This PR unwraps as many `TargetInvocationException` layers as are present. It partially implements #205.
=> Unwrap multiple target invocation exceptions

docs/docs/authorization.md, docs/docs/getting-started.md, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
Changes the docs to use `ExecuteRequestAsync` instead of `ExecuteRequest`. This not only provides a performance improvement, it also works around an apparent bug. In a production app, we were experiencing extremely high CPU when using the synchronous version of `ExecuteRequest`, rendering the web server unusable. The problem didn't always occur; it seemed to be related to the frequency of GraphQL queries, with successive calls getting progressively slower while always consuming an entire core. Switching to async solved the problem. Switching to async resolved the problem.
The high CPU issue doesn't occur when just calling `ExecuteRequest` directly. I tried adding high frequency calls to a unit test in QueryTests.cs, and they worked just fine. The problem appears to be related to …
=> Document HTTP request using async

src/EntityGraphQL/Extensions/Nullability/NullabilityInfo.cs, src/EntityGraphQL/Extensions/Nullability/NullabilityInfoContext.cs, src/EntityGraphQL/Extensions/Nullability/NullabilityInfoExtensions.cs, src/EntityGraphQL/Extensions/TypeExtensions.cs, src/EntityGraphQL/Schema/ArgType.cs, src/EntityGraphQL/Schema/ControllerType.cs, src/EntityGraphQL/Schema/GqlTypeInfo.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/Util/NullableReferenceTypeTests.cs
main change is to make the following correct, although the changes got a bit wider than i'd like and I'm sure there's still issues with the IsNullable method assuming it should look at the first or last byte (unsure if you've ever read on how this byte array works)
```
//public IEnumerable<Test> Tests { get; set; } = new List<Test>();
Assert.Contains("tests: [Test!]!", schemaString);
//public IEnumerable<Test>? Tests2 { get; set; }
Assert.Contains("tests2: [Test!]\r\n", schemaString);
//public IEnumerable<Test?> Tests3 { get; set; } = new List<Test>();
Assert.Contains("tests3: [Test]!", schemaString);
//public IEnumerable<Test?>? Tests4 { get; set; }
Assert.Contains("tests4: [Test]\r\n", schemaString);
```
=> Fixes nullable lists

src/EntityGraphQL.AspNet/Extensions/EntityGraphQLAspNetServiceCollectionExtensions.cs, src/EntityGraphQL/Compiler/EntityGraphQLCompilerException.cs, src/EntityGraphQL/Compiler/EntityGraphQLValidationException.cs, src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionStatement.cs, src/EntityGraphQL/EntityGraphQLArgumentException.cs, src/EntityGraphQL/EntityGraphQLException.cs, src/EntityGraphQL/EntityGraphQLFieldException.cs, src/EntityGraphQL/IExposableException.cs, src/EntityGraphQL/Schema/FieldExtensions/ConnectionPaging/ConnectionEdgeExtension.cs, src/EntityGraphQL/Schema/FieldExtensions/OffsetPaging/OffsetPagingExtension.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaBuilderOptions.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/ErrorTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
This change stops leaking exceptions into the 'errors' field on a result. This has been raised here: https://github.com/EntityGraphQL/EntityGraphQL/issues/205  
When running in development (read via `IWebHostEnvironment.IsEnvironment("Development")` or when manually creating `SchemaProvider`), messages of exceptions will not be dumped out into the 'errors' field of a query result, unless they implement the newly created (and empty) interface `IExposableException`.
Part of this change was to modify where we're catching and unwrapping exceptions (for example, see [src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs](https://github.com/EntityGraphQL/EntityGraphQL/compare/master...rjrudman:EntityGraphQL:feature/205?expand=1#diff-2649053fc8256fcc5e8681e63a4eeb6c04ce96d96b04b83cafc …
=> Do not leak exception messages in 'errors'

src/EntityGraphQL/Compiler/GqlNodes/GraphQLListSelectionField.cs, src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/tests/EntityGraphQL.Tests/QueryTests/UnionTests.cs
as per first issue in #264 
interface/union queries used to require you to query for at least 2 of the subtypes at once.
=> Fix for interface/union types when selecting only single subtype

src/EntityGraphQL/Schema/MethodField.cs, src/EntityGraphQL/Schema/SchemaGenerator.cs, src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs, src/tests/EntityGraphQL.Tests/QueryTests/ArgumentTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs
believe this makes default values in mutaitons work
eg
```
[GraphQLMutation]
public int DefaultValueTest(int valueWithDefault = 8)
{
return valueWithDefault;
}
```
=> support default values in c# methods

src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/ErrorTests.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
Rather than returning duplicate error messages, we now only return distinct messages. 
Raised here: https://github.com/EntityGraphQL/EntityGraphQL/pull/262#pullrequestreview-1131619981
=> #205 - Only return unique error messages

src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/tests/EntityGraphQL.Tests/QueryTests/UnionTests.cs
So it appears the Expression.TypeIs strategy for interfaces/unions causes entityframework to perform extra queries when AsSplitQuery is enabled
I made a tweak in 4.1 to fix some cases around querying unions without querying multiple types, this meant that when used in conjunction with AsSplitQuery it queried the database once for each type and twice for the base type.
This PR fixes the twice for the base type issue (but not for the once for each type issue).
=> bugfix: stop double sql query on base type (4.1 regression)

src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/tests/EntityGraphQL.Tests/QueryTests/InheritanceTests.cs
when using strawberry shake client it seems to make queries like this without much control, so i guess it make sense to support them
```
query {
animals {
__typename
id        
... on Cat {
id
}
...on Dog {
id
}
}
}
```
=> bugfix: remove duplicate fields when creating expression

src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/tests/EntityGraphQL.Tests/QueryTests/InheritanceTests.cs, src/tests/EntityGraphQL.Tests/TestAbstractDataContext.cs
mutations were running the wrong code if they returned an interface/union type
=> Fix for mutation when they return interfaces/unions

src/EntityGraphQL/Schema/AllowedException.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/WhitelistedException.cs, src/tests/EntityGraphQL.Tests/ErrorTests.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
Related to #270  
This change allows consumers of the library to specify whitelisted exceptions on top of the provided `IExposableException`.
This is required because users may not be able to modify the exceptions being thrown in order to have them implement `IExposableException`.
Exceptions may be whitelisted with an exact type match, or whitelisted including all types that inherit it.
=> Implement whitelisted exceptions

src/EntityGraphQL.AspNet/Extensions/RuntimeTypeJsonConverter.cs, src/tests/EntityGraphQL.AspNet.Tests/RuntimeTypeJsonConverterTests.cs
for #288 
* added some extra tests - none replicated the issue, had to verify the fix by referencing in the example project
* this is one of 3 possible fixes i found
1) remove RuntimeJsonConverter from options on nested calls
2) detect isPrimitive like we do with 'is string' and handle it separately
3) (this fix) pass the type down to the serialize function
=> #288 - fixing stack overflow in runtimejsonconverter

src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs
the fix for #221 added a expression.condition, this accidentally evaluates ResolveWithService calls twice which can make multiple db requests.
Using Expression.Coalesce is a better choice but does mean we need to return an empty list instead of null (don't think that's a bad thing but it is a change).
=> ResolveWithService being called twice due to Expression.Condition 

docs/docs/validation.md, src/EntityGraphQL.AspNet/Extensions/EntityGraphQLAspNetServiceCollectionExtensions.cs
When GraphQLValidator is added with `Transient` lifetime, a new instance gets created whenever GetService is called.
This causes the system to never report any errors that are added to the validator.
Adding the validator service with a `Scoped` lifetime means the validator lives through the entire request and any errors that were added can be returned in the response.
[ServiceLifetime docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicelifetime)
=> Change AddGraphQLValidator service lifetime to Scoped

src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/EntityGraphQL/Extensions/TypeExtensions.cs
After upgrading to .NET 8, queries with a DateTime filter stopped working.
For example:
```
{
activities(filter: "createdAt > \"2023-07-27T13:52:56.00\"") { 
totalItems
}
}
```
Would produce this error:
```
{
"error": {
"errors": [
{
"message": "No coercion operator is defined between types 'System.String' and 'System.Nullable`1[System.DateTime]'."
}
]
}
}
```
`ConvertLeftOrRight` was trying to convert a non-nullable string straight into a nullable DateTime.
I altered this to instead change the non-nullable type into a **nullable version of the same type**, which allows the rest of the conversions to take place correctly.
=> fix conversion of non-nullable/nullable types

src/EntityGraphQL/Schema/ArgType.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs
Annotating a mutation argument with [Description("some description")] now sets the argument's description rather than the name
=> Fix #337 - Description attribute accidentally updating name instead of description

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs
First of all, thanks for the library! I've just started exporing it and everything is working smoothly so far. Well, almost everything, that's why I'm submitting the PR.
Some of the entities in the database context I've been experimenting with use [NpgsqlTsVector](https://www.npgsql.org/doc/api/NpgsqlTypes.NpgsqlTsVector.html) type that causes `SchemaBuilder` to fail with `ArgumentException` (Incorrect number of arguments supplied for call to method 'Lexeme get_Item(Int32)' (Parameter 'property')).
This happens when it tries to build an expression for the indexer property because such properties need an addition argument. Given that such properties are, in fact, methods, I think they should be discarded altogether.
=> Fix ArgumentException when an entity has indexer property

CHANGELOG.md, src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/EntityGraphQL/Compiler/QueryWalkerHelper.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/Field.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/EntityQuery/EntityQueryCompilerTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs
I noticed that some error messages returned are harder to quickly grasp. i think this should make them more readable. should i do it for all exceptions all variables or is this enough for now?
=> make error variable values more distinctive

CHANGELOG.md, src/EntityGraphQL.AspNet/EntityGraphQL.AspNet.csproj, src/EntityGraphQL.AspNet/Extensions/EntityGraphQLWebApplicationExtensions.cs, src/EntityGraphQL.AspNet/WebSockets/GraphQLWSMessage.cs, src/EntityGraphQL.AspNet/WebSockets/GraphQLWebSocketServer.cs, src/EntityGraphQL.AspNet/WebSockets/IGraphQLWebSocketServer.cs, src/EntityGraphQL.AspNet/WebSockets/WebSocketSubscription.cs, src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLDocument.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLQueryStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionStatement.cs, src/EntityGraphQL/QueryRequest.cs, src/EntityGraphQL/Schema/FieldExtensions/Sorting/SortExtension.cs, src/EntityGraphQL/Schema/FieldExtensions/Sorting/UseSortExtension.cs, src/EntityGraphQL/Schema/MethodField.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Subscriptions/Broadcaster.cs, src/EntityGraphQL/Subscriptions/GraphQLSubscription.cs, src/tests/EntityGraphQL.AspNet.Tests/GraphQLWebSocketServerTests.cs, src/tests/EntityGraphQL.Tests/PersistedQueriesTests.cs, src/tests/EntityGraphQL.Tests/SortTests/SortTests.cs
Gives an option when using `.UseSort()` to tell it to build the sort argument type from the schema fields of the type we are sorting instead of the dotnet properties.
Addressing #365
=> support building sort type from schema fields

src/EntityGraphQL.AspNet/Extensions/EntityGraphQLAspNetServiceCollectionExtensions.cs
As the title suggest, this PR simply adds the ability to disable introspection when calling the AddGraphQLSchema extension method(s).
Thanks for this awesome library!
=> Allow specifying `introspectionEnabled` when calling the AddGraphQLSchema extension method(s)

src/EntityGraphQL/Compiler/EntityQuery/Grammar/Binary.cs, src/tests/EntityGraphQL.Tests/EntityQuery/FilterExtensionTests.cs
Prior to 5.4.0, you could filter with enum values using single quotes like so:
```
users (filter: "status == 'ACTIVE'") 
```
This is broken under the new parser, which seems to prefer
```
users (filter: "status == ACTIVE")
```
For backwards compatibility, I think it would be best to support strings again? Added a fix and test in this PR.
=> Fix filtering - comparing enums with strings

src/EntityGraphQL/Compiler/EntityQuery/Grammar/EntityQueryParser.cs
Example query:
```
{ 
users (filter: "isActive == true && isActive == false") { 
name 
} 
}
```
5.3.0: 
- Worked as expected, returns no results.
- Generated the following expression:
```
p_EFCoreDemoContext.Users
.Where(q_User => ((q_User.IsActive == True) AndAlso (q_User.IsActive == False)))
.Select(p_User => new Dynamic_users_...() {name = p_User.Name})}	
```
5.4.0: 
- Pomelo MySQL Provider throws a MySqlException due to an error in SQL syntax
- However, SqlServer provider continues to behave fine
- This lib generates the following expression, uses of `And` instead of `AndAlso`.
```
p_EFCoreDemoContext.Users
.Where(q_User => ((q_User.IsActive == True) And (q_User.IsActive == False)))
.Select(p_User => new Dynamic_users_...() {name = p_User.Name})
```
Can we update the parser to use …
=> fix: use AndAlso for queryparser to match behaviour of older versions

CHANGELOG.md, src/Benchmarks/CacheBenchmarks.cs, src/EntityGraphQL.AspNet/WebSockets/WebSocketSubscription.cs, src/EntityGraphQL/Compiler/EntityGraphQLQueryWalker.cs, src/EntityGraphQL/Compiler/EntityQuery/EntityQueryCompiler.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLField.cs, src/EntityGraphQL/Compiler/GqlNodes/CompileContext.cs, src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLDocument.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLQueryStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionStatement.cs, src/EntityGraphQL/Compiler/GraphQLCompiler.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/QueryRequestContext.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.AspNet.Tests/PoliciesTests.cs, src/tests/EntityGraphQL.Tests/EntityQuery/EntityQueryCompilerTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/ServiceFieldTests.cs, src/tests/EntityGraphQL.Tests/RoleAuthorizationTests.cs
User credentials were used when compiling from the query string to our nodes. This removes that and does the access checks at expression building time.
=> fix #398 - do access checks at expression build time not string query

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaBuilderOptions.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderFromObjectTests.cs
This PR adds the ability to ignore specific data annotations when building the schema. 
Key changes:
- Added a new `IgnoreDataAnnotations` property to `SchemaBuilderOptions`
- Updated `SchemaBuilder.ShouldIncludeMember` to check for ignored annotations
- Added a unit test to verify the new functionality
This feature allows users to exclude fields with certain data annotations from the GraphQL schema, providing more flexibility in schema generation.
=> Add option to ignore specific data annotations

src/EntityGraphQL/Schema/FieldExtensions/ConnectionPaging/ConnectionEdgeExtension.cs, src/EntityGraphQL/Schema/FieldExtensions/ConnectionPaging/ConnectionHelper.cs, src/tests/EntityGraphQL.Tests/ConnectionPaging/ConnectionPagingTests.cs, src/tests/EntityGraphQL.Tests/ConnectionPaging/SkipTakeTests.cs
I've been sitting on this one for a few (16) months. I figured I might as well push it up when I saw an issue come in for it.
=> fix #427 - fix ConnectionPaging GetSkipNumber off-by-one when using Before arg, fix handling when Last > BeforeNum

src/EntityGraphQL/Compiler/EntityQuery/Grammar/EntityQueryParser.cs
Assuming the use of bitwise `ExpressionType.Or` was not deliberate. I think `ExpressionType.OrElse` is the correct expression type here :)
=> fix: replace bitwise "ExpressionType.Or" with conditional OrElse

src/EntityGraphQL/Compiler/EntityGraphQLQueryWalker.cs, src/EntityGraphQL/Compiler/EntityQuery/Grammar/IdentityExpression.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLField.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLQueryField.cs, src/EntityGraphQL/Compiler/GqlNodes/CompileContext.cs, src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLDirective.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLDocument.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLFragmentStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLListSelectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLObjectProjectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLScalarField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionField.cs, src/EntityGraphQL/Compiler/GqlNodes/IGraphQLNode.cs, src/EntityGraphQL/Compiler/Util/ArgumentUtil.cs, src/EntityGraphQL/Extensions/DictionaryExtensions.cs, src/EntityGraphQL/Schema/BaseField.cs, src/EntityGraphQL/Schema/Field.cs, src/EntityGraphQL/Schema/IField.cs, src/EntityGraphQL/Schema/MethodField.cs, src/EntityGraphQL/Schema/PropertyTracker/IPropertySetTrackingDto.cs, src/EntityGraphQL/Schema/PropertyTracker/PropertySetTrackingDto.cs, src/examples/demo/Mutations/DemoMutations.cs, src/examples/demo/schema.graphql
Implementation for #441. Inherit mutation model from `PropertySetTrackingDto` so you can use `IsSet("PROPERTY_NAME")` method to check if property was provided in query.
Arguments type changed from `Dictionary<string, object>?` to `Dictionary<string, object?>?`.
I have changed `ProcessArguments` to return arguments with null value. Please check `BuildArgumentFromMember` function, it may not work correctly.
=> PropertySetTrackingDto, Arguments as Dictinary<string,object?>

src/EntityGraphQL.AspNet/Extensions/EntityGraphQLEndpointRouteExtensions.cs, src/tests/EntityGraphQL.AspNet.Tests/EntityGraphQLEndpointRouteExtensionsTests.cs
When using `HttpClient.PostAsJsonAsync()` to call the GraphQL endpoint (`EntityGraphQLEndpointRouteExtensions.MapGraphQL`), the request fails with `400 Bad Request`. This happens because `PostAsJsonAsync`:
- Sets `Transfer-Encoding: chunked`
- Does **not** set `Content-Length`
The current implementation in `EntityGraphQLEndpointRouteExtensions.MapGraphQL<T>()` rejects all requests where `ContentLength == null` or `0`, making it incompatible with chunked transfers — despite chunked encoding being fully compliant with HTTP/1.1.
This behavior makes the GraphQL endpoint incompatible with a common usage of HTTP client libraries.
---
In `MapGraphQL<TQueryType>`, we now:
- Check for `Transfer-Encoding: chunked`
- If the request is chunked, we no longer reject it for having no `Content-Length` …
=> fix `EntityGraphQLEndpointRouteExtensions.MapGraphQL` to support chunked requests sent via PostAsJsonAsync

src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/tests/EntityGraphQL.Tests/IntrospectionTests/IntrospectionTests.cs
According to the GraphQL spec, enums are valid input types and must not be skipped when constructing input fields. This change ensures enum-typed fields are included during schema introspection.
- Spec references:
- [Input Values](https://spec.graphql.org/October2021/#sec-Input-Values)
- [Enums](https://spec.graphql.org/October2021/#sec-Enums)
Previously, enum-typed fields were excluded from input values during introspection. This led to a schema that diverged from the GraphQL spec and could break clients relying on enum inputs. This PR removes that exclusion so enums appear correctly in introspection and can be used as intended.
- Remove exclusion of enum-typed fields in `SchemaIntrospection` when building input values.
- Add unit test verifying enum-typed input fields are exposed via …
=> Fix: Include enum-typed input fields in introspection per GraphQL spec
