src/EntityGraphQL/Compiler/GraphQLCompiler.cs, src/EntityGraphQL/Compiler/GraphQLMutationNode.cs, src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/EntityGraphQL/LinqQuery/DefaultMethodProvider.cs
This way its easier to find the original source of the exception.
=> Include inner exception when wrapping exceptions.

docs/content/introduction.md
Changed **LING** to **LINQ** and added links to external docs
=> Fixed a typo in README

EntityGraphQL.sln, docs/content/schema-creation/03-types.md, src/EntityGraphQL/Compiler/GqlNodes/GraphQLListSelectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLObjectProjectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLScalarField.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/ISchemaType.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaGenerator.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaProviderTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/TestAbstractDataGraphSchema.cs, src/tests/EntityGraphQL.Tests/SchemaTests/TestObjectGraphSchema.cs, src/tests/EntityGraphQL.Tests/TestAbstractDataContext.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
Not quite working yet - have an issue where __typename returns the base type instead of the object type itself.  But figured I'd start the chat to see if I'm on the right track.
`AddField("__typename", t => name, "Type name").IsNullable(false);`
is obviously always going to show the base type.
`AddField("__typename", t => schema.Type(t!.GetType().Name).Name, "Type name").IsNullable(false);`
Works for most the tests, but seems to break on getting typename on a relationship (as it's coming through as IEnumerable
=> Attempt at adding interfaces

src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/Util/NullableReferenceTypeTests.cs
No library changes, just added introspection tests to ensure it was working correctly
=> Add some introspection tests for nullable ref types

src/EntityGraphQL/Schema/Models/Introspection.cs, src/EntityGraphQL/Schema/SchemaIntrospection.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs
turns out i didn't realise that ToGraphQLSchema works differently than introspection, so adding some PR's to fix my various PRs
=> fix: interfaces in regards to introspection

CHANGELOG.md, docs/content/schema-creation/03-types.md, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/ISchemaType.cs, src/EntityGraphQL/Schema/MutationType.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/EntityGraphQL/Schema/SchemaType.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs, src/tests/EntityGraphQL.Tests/SchemaTests/TestAbstractDataGraphSchema.cs
=> #155 clean up interfaces

src/EntityGraphQL/Compiler/EntityGraphQLQueryWalker.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLFragmentStatement.cs, src/tests/EntityGraphQL.Tests/QueryTests/InheritanceTests.cs
was causing a casting exception before in cases when you use an inline fragment in a fragment
=> bugfix: support GraphQLFragmentStatement in inline fragments

src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/tests/EntityGraphQL.Tests/EntityQuery/EntityQueryCompilerTests.cs
=> bugfix: allow fully qualified enums

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationMethodParameterTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/MutationTests.cs, src/tests/EntityGraphQL.Tests/MutationTests/PeopleMutations.cs
InputTypes getting arguments in 3.0 #183
=> InputTypes getting arguments in 3.0 #183

src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.Tests/IntrospectionTests/IntrospectionTests.cs
=>  InputValue type is being registered under wrong name #184

src/EntityGraphQL/Schema/SchemaBuilder.cs, src/tests/EntityGraphQL.Tests/SchemaTests/GraphQLSchemaGenerateTests.cs
IgnoreTypes doesn't ignore enumerable types #181
=> IgnoreTypes doesn't ignore enumerable types #181

src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/tests/EntityGraphQL.Tests/EntityQuery/EntityQueryCompilerTests.cs
=> Was using default enum value for fully qualified enums instead of the parsed value

src/tests/EntityGraphQL.Tests/SchemaTests/SchemaBuilderTests.cs
This is a test for #199. The test passed. I'm submitting the PR anyway, since it includes the nuance of `UpdateType` and `AddField`, in case it's deemed worthy of inclusion for regression testing purposes.
=> Test that referenced types are ignored

docs/docs/directives/schema-directives.md, docs/docs/other-extensibility/extension-attribute.md, src/EntityGraphQL/Schema/BaseField.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/Directives/DeprecatedDirective.cs, src/EntityGraphQL/Schema/Directives/SchemaDirectiveExtensions.cs, src/EntityGraphQL/Schema/Directives/SpecifiedByDirective.cs, src/EntityGraphQL/Schema/Directives/TypeSystemDirectiveLocation.cs, src/EntityGraphQL/Schema/ExtensionAttribute.cs, src/EntityGraphQL/Schema/ISchemaProvider.cs, src/EntityGraphQL/Schema/SchemaBuilder.cs, src/EntityGraphQL/Schema/SchemaBuilderOptions.cs, src/EntityGraphQL/Schema/SchemaProvider.cs, src/tests/EntityGraphQL.AspNet.Tests/AuthorizeDirective.cs, src/tests/EntityGraphQL.AspNet.Tests/PoliciesTests.cs
@bzbetty any thoughts on these changes?
=> refactor registering attribute handlers

docs/docs/entity-framework.md, docs/docs/schema-creation/subscriptions.md, src/EntityGraphQL.AspNet/WebSockets/GraphQLWebSocketServer.cs, src/EntityGraphQL.AspNet/WebSockets/WebSocketSubscription.cs, src/EntityGraphQL/Compiler/EntityGraphQLQueryWalker.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLField.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLQueryField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLObjectProjectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionStatement.cs, src/EntityGraphQL/Schema/SubscriptionType.cs, src/EntityGraphQL/Subscriptions/Broadcaster.cs, src/examples/subscriptions/ChatContext.cs, src/examples/subscriptions/ChatGraphQLSchema.cs, src/examples/subscriptions/Mutations/ChatMutations.cs, src/examples/subscriptions/Program.cs, src/examples/subscriptions/Services/ChatEventService.cs, src/examples/subscriptions/Services/ChatService.cs, src/examples/subscriptions/Subscriptions/ChatSubscriptions.cs, src/examples/subscriptions/wwwroot/dist/index.html, src/examples/subscriptions/wwwroot/src/site.jsx
Fixes #226
allows execution of a full query graph expression on a subscription event
=> full graph query on subscriptions

docs/docs/schema-creation/mutations.md
updated mutation argument syntax to 4.0.0
=> Update mutations.md docs for 4.0.0 syntax

src/tests/EntityGraphQL.Tests/QueryTests/QueryTests.cs, src/tests/EntityGraphQL.Tests/TestDataContext.cs
=> Add async field unit test

docs/docs/serialization-naming/serialization-naming.md, src/EntityGraphQL.AspNet/Extensions/DefaultGraphQLResponseSerializer.cs, src/EntityGraphQL.AspNet/Extensions/RuntimeTypeJsonConverter.cs, src/tests/EntityGraphQL.AspNet.Tests/RuntimeTypeJsonConverterTests.cs, src/tests/EntityGraphQL.Tests/SerializationTests.cs
as per #264 .net JSonSerializer doesnt' handle subclasses very well.
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-6-0
=> support for serializing subclasses (#264)

src/EntityGraphQL.AspNet/Extensions/DefaultGraphQLResponseSerializer.cs, src/EntityGraphQL.AspNet/Extensions/RuntimeTypeJsonConverter.cs, src/tests/EntityGraphQL.AspNet.Tests/RuntimeTypeJsonConverterTests.cs
Now handles dictionaries and fields
=> Serialization fixes for #264

src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs
=> fix for #221

src/Benchmarks/CompileFiltersBenchmarks.cs
=> PR for #275 performance tests

docs/docs/field-extensions/filtering.md, src/EntityGraphQL/Compiler/EntityQuery/DefaultMethodProvider.cs, src/EntityGraphQL/Compiler/EntityQuery/EntityQueryNodeVisitor.cs, src/EntityGraphQL/Compiler/EntityQuery/IMethodProvider.cs, src/tests/EntityGraphQL.Tests/EntityQuery/DefaultMethodProviderTests.cs
Update DefaultMethodProvider to handle string methods
=> Add string methods to DefaultMethodProvider

CHANGELOG.md, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLField.cs, src/EntityGraphQL/Compiler/GqlNodes/BaseGraphQLQueryField.cs, src/EntityGraphQL/Compiler/GqlNodes/ExecutableGraphQLStatement.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLCollectionToSingleField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLExtractedField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLFragmentSpreadField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLInlineFragmentField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLListSelectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLMutationField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLObjectProjectionField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLScalarField.cs, src/EntityGraphQL/Compiler/GqlNodes/GraphQLSubscriptionField.cs, src/EntityGraphQL/Compiler/Util/ExpressionReplacer.cs, src/EntityGraphQL/Compiler/Util/ExpressionUtil.cs, src/EntityGraphQL/Compiler/Util/ParameterReplacer.cs, src/EntityGraphQL/Schema/BaseSchemaTypeWithFields.cs, src/EntityGraphQL/Schema/IField.cs, src/tests/EntityGraphQL.Tests/QueryTests/InheritanceAdvancedTest.cs, src/tests/EntityGraphQL.Tests/QueryTests/ServiceFieldTests.cs, src/tests/EntityGraphQL.Tests/QueryTests/UnionTests.cs
WIP - have some broken tests, haven't gotten head around how to fix.
=> Working on fixes to method and service calls on interfaces/unions

docs/docs/getting-started.md
azure functions sample and small improvement
=> add documentation for getting started with azure functions

src/EntityGraphQL/Compiler/Util/ArgumentUtil.cs
was null ref later in the code
=> Support for directives without arguments

src/EntityGraphQL/Compiler/EntityQuery/DefaultMethodProvider.cs, src/tests/EntityGraphQL.Tests/EntityQuery/FilterExtensionTests.cs
fix for https://github.com/EntityGraphQL/EntityGraphQL/issues/435
=> fix issue with isAny on root
